newFunction();
function newFunction() {
	var AniCredits = angular.module('AniCredits', []);

	AniCredits.controller('DisplayPanel', function ($scope) {
		$scope.events = [
			{ 'title': 'A Good Librarian Like a Good Shepherd', 'credit': '© 2014 AUGUST /Shirasaki Tsugumi and Stray Lambs', 'site': 'http://www.daito-anime.com/' },
			{ 'title': 'Amagi Brilliant Park', 'credit': '© Kadokawa Corporation 2014', 'site': 'http://amaburi.jp/' },
			{ 'title': 'Cardfight!! Vanguard G', 'credit': '©bushiroad All Rights Reserved.', 'site': 'http://cf-vanguard.com/' },
			{ 'title': 'Celesital Method', 'credit': '©霧弥湖町観光協会', 'site': 'http://sora-no-method.jp/' },
			{ 'title': 'Chaika the Coffin Princess: Avenging Battle', 'credit': '©2014 榊一郎・Nitroplus／ＫＡＤＯＫＡＷＡ 富士見書房刊／「棺姫のチャイカAB」製作委員会', 'site': 'http://chaika-anime.jp/' },
			{ 'title': 'Cross Ange Rondo of Angel and Dragon', 'credit': '© SUNRISE/PROJECT ANGE', 'site': 'http://crossange.com/' },
			{ 'title': 'Denki-gai no Honya-san', 'credit': '© 2014 Muzuasato/PUBLISHED BY KADOKAWA CORPORATION MEDIA FACTORY/UmaNoHone Comic', 'site': 'http://umanohone.us/' },
			{ 'title': 'Fate/Stay Night: Unlimited Blade Works', 'credit': '©TYPE-MOON,ufotable,FSNPC', 'site': 'http://www.fatestaynightusa.com/' },
			{ 'title': 'Milpom★', 'credit': '©OSO/BNP,COVER,ASOBISYSTEM,VITHMIC', 'site': 'http://milpom.com/' },
			{ 'title': 'Garo: The Carved Seal of Flame', 'credit': '©2014「炎の刻印」雨宮慶太／東北新社', 'site': 'http://garo-project.jp/ANIME/' },
			{ 'title': 'Girl Friend BETA', 'credit': 'Copyright © CyberAgent, Inc. All Rights Reserved.', 'site': 'http://girlfriend-kari.jp/' },
			{ 'title': 'Gonna be the Twin-Tails!!', 'credit': '©水沢 夢・小学館／製作委員会はツインテールになります。 ', 'site': 'http://www.tbs.co.jp/anime/ore_twi/' },
			{ 'title': 'Gugure! Kokkuri-san', 'credit': '©遠藤ミドリ／スクウェアエニックス・「繰繰れ！コックリさん」製作委員会', 'site': 'http://www.jp.square-enix.com/magazine/joker/series/gugure_kokkurisan/' },
			{ 'title': 'Gundam Build Fighters Try', 'credit': '©創通・サンライズ・テレビ東京', 'site': 'http://gundam-bf.net/' },
			{ 'title': 'MOBILE SUIT GUNDAM IRON-BLOODED ORPHANS', 'credit': '©SOTSU・SUNRISE・MBS', 'site': 'http://g-tekketsu.com/index.html' },
			{ 'title': 'Saint Seiya -soul of gold-', 'credit': ' ©Masami Kurumada／Saint Seiya soul of gold Production committee', 'site': 'http://tamashii.jp/special/seiya_sog/' },
			{ 'title': 'Gundam: Reconguista in G', 'credit': '©創通・サンライズ・ＭＢＳ', 'site': 'http://www.g-reco.net/' },
			{ 'title': 'Hi☆sCoool! Sega Hard Girl', 'credit': '©SEGA/セハガガ学園理事会', 'site': 'http://shg.sega.jp/' },
			{ 'title': 'I Can\'t Understand What My Husband Is Saying', 'credit': '©クール教信者/一迅社・旦那が製作委員会2014', 'site': 'http://www.dreamcreation.co.jp/danna/' },
			{ 'title': 'Laughing Under the Clouds', 'credit': '© Karakara Kemuri / MAG Garden', 'site': 'http://dontenniwarau.com/' },
			{ 'title': 'Log Horizon', 'credit': '©橙乃ままれ・KADOKAWA／NHK・NEP', 'site': 'http://www9.nhk.or.jp/anime/loghorizon/index.html' },
			{ 'title': 'Lord Marksman and Vanadis', 'credit': '©2014 川口士・株式会社KADOKAWA メディアファクトリー刊／魔弾の王と戦姫製作委員会', 'site': 'http://www.madan-anime.jp/' },
			{ 'title': 'Magic Kaito 1412', 'credit': '©青山剛昌／小学館・読売テレビ・A-1 Pictures 2014', 'site': 'http://www.ytv.co.jp/magickaito/' },
			{ 'title': 'Mushishi: The Next Chapter 2nd Season', 'credit': '©漆原友紀／講談社・アニプレックス', 'site': 'http://www.mushishi-anime.com/' },
			{ 'title': 'Ohenro. Eighty-Eight Steps Chronicle', 'credit': '©ufotable', 'site': 'http://ufotable.com/ohenro/' },
			{ 'title': 'Parasyte', 'credit': '© 岩明均／講談社・VAP・NTV・4cast', 'site': 'http://ufotable.com/ohenro/' },
			{ 'title': 'Psycho-Pass', 'credit': '© PSYCHO-PASS Committee', 'site': 'http://psycho-pass.com/' },
			{ 'title': 'Rage of Bahamut: Genesis', 'credit': '© Cygames/MAPPA/BAHAMUT GENESIS', 'site': 'http://shingekinobahamut-genesis.jp/' },
			{ 'title': 'Ronia the Robber\'s Daughter', 'credit': '©NHK・NEP・Dwango, licensed by Saltkrakan AB, The Astrid Lindgren Company', 'site': 'http://www9.nhk.or.jp/anime/ronja/' },
			{ 'title': 'Ushinawareta Mirai wo Motomete', 'credit': '© Atelier Hi-Key/In Search of the Lost Future production committee', 'site': 'http://ushinawareta-mirai.com/' },
			{ 'title': 'Selector WIXOSS', 'credit': '©LRIG/Project Selector', 'site': 'http://selector-wixoss.com/' },
			{ 'title': 'SHIROBAKO', 'credit': '©「SHIROBAKO」製作委員会', 'site': 'http://www.shirobako-anime.com/' },
			{ 'title': 'Tenchi Muyo! Love', 'credit': '©梶島正樹／愛・天地無用！', 'site': 'http://www.ai-tenchi.jp/' },
			{ 'title': 'Terra Formars', 'credit': '©貴家悠・橘賢一／集英社・Project TERRAFORMARS', 'site': 'http://terraformars.tv/' },
			{ 'title': 'Orenchi no Furo Jijō', 'credit': '©2014いときち/株式会社KADOKAWA メディアファクトリー刊/オレフロ製作委員会', 'site': 'http://www.orefuro.jp/' },
			{ 'title': 'The Fruit of Grisaia', 'credit': '©Frontwing/Project GRISAIA', 'site': 'http://www.grisaia-anime.com/' },
			{ 'title': 'The Seven Deadly Sins', 'credit': '©鈴木央・講談社／「七つの大罪」製作委員会・MBS', 'site': 'http://www.7-taizai.net/' },
			{ 'title': 'Trinity Seven', 'credit': '©サイトウケンジ・奈央晃徳／ＫＡＤＯＫＡＷＡ 富士見書房／トリニティセブン製作委員会', 'site': 'http://trinity-7.com/' },
			{ 'title': 'When Supernatural Battles Became Commonplace', 'credit': '©2014　望 公太・ＳＢクリエイティブ／泉光高校文芸部', 'site': 'http://inou-anime.com/' },
			{ 'title': 'Wolf Girl and Black Prince', 'credit': '©八田鮎子／集英社・「オオカミ少女と黒王子」製作委員会', 'site': 'http://www.ookamishojo-anime.jp/' },
			{ 'title': 'World Trigger', 'credit': '©葦原大介／集英社・テレビ朝日・東映アニメーション', 'site': 'http://worldtrigger.info/' },
			{ 'title': 'Yona of the Dawn', 'credit': '© Mizuho Kusanagi, Hakusensha/Akatsuki no Yona Production Committee', 'site': 'http://marv.jp/special/yona/' },
			{ 'title': 'Your Lie in April', 'credit': '©新川直司・講談社／「四月は君の嘘」製作委員会', 'site': 'http://www.kimiuso.jp/' },
			{ 'title': 'Yowamushi Pedal: Grande Road', 'credit': '©渡辺航（週刊少年チャンピオン）／弱虫ペダル製作委員会', 'site': 'http://yowapeda.com/' },
			{ 'title': 'Yuuna Yuuki is a Hero', 'credit': '©2014 Project 2H', 'site': 'http://yuyuyu.us/' },
			{ 'title': 'Abarenbō Rikishi!! Matsutarō', 'credit': '© Tetsuya Chiba/TV Asahi, Toei Animation © C/T, T', 'site': 'http://www.toei-anim.co.jp/tv/matsutaro/' },
			{ 'title': 'Baby Steps', 'credit': '© Hikaru Katsuki, Kodansha/NHK, NEP', 'site': 'http://www9.nhk.or.jp/anime/babysteps' },
			{ 'title': 'Black Bullet', 'credit': '© 2013 Shiden Kanzaki/Kadokawa/ASCII Media Works/Black Bullet Production Committee', 'site': 'http://www.black-bullet.net/' },
			{ 'title': 'Blade and Soul', 'credit': '© NCSoft, Blade & Soul Anime Production Committee', 'site': 'http://us.bladeandsoul.com/en/' },
			{ 'title': 'Break Blade (TV)', 'credit': '© Yunosuke Yoshinaga, Flex Comix/Broken Blade Production Committee', 'site': 'http://breakblade.jp/' },
			{ 'title': 'Brynhildr in the Darkness', 'credit': '© Lynn Okamoto/Shueisha, Brynhildr in the Darkness Production Committee', 'site': 'http://www.brynhildr.jp/' },
			{ 'title': 'Captain Earth', 'credit': '©BONES/CAPTAIN EARTH COMMITEE, MBS', 'site': 'http://captain-earth.net/' },
			{ 'title': 'Chaika the Coffin Princess', 'credit': '© Ichiro Sakaki, Namaniku ATK (Nitroplus)', 'site': 'http://chaika-anime.jp/' },
			{ 'title': 'Daimidaler the Sound Robot', 'credit': '©Asaki Nakama/ENTERBRAIN/PENGUIN EMPIRE', 'site': 'http://penguin-empire.com/' },
			{ 'title': 'Dai-Shogun - Great Revolution', 'credit': '©2014 Project-D', 'site': 'http://daishogun-anime.jp/' },
			{ 'title': 'Shin Gekijō-ban Initial D Legend 3 -Yumeutsutsu- (movie)', 'credit': '©しげの秀一/講談社・2014新劇場版「頭文字D」製作委員会', 'site': 'http://initiald-movie.com/' },
			{ 'title': 'Date A Live II', 'credit': '© 2013 Koushi Tachibana, Tsunako/Fujimi Shobo/Date A Live Production Committee', 'site': 'http://date-a-live.net/' },
			{ 'title': 'Dragonar Academy', 'credit': '©2014 Shiki Mizuchi, PUBLISHED BY KADOKAWA CORPORATION MEDIAFACTORY/Dragonar Project', 'site': 'http://www.seikokutv.com/' },
			{ 'title': 'Haikyuu!!', 'credit': '© Haruichi Furudate, Shueisha/Haikyuu!! Production Committee', 'site': 'http://www.j-haikyu.com/' },
			{ 'title': 'JoJo\'s Bizaare Adventure', 'credit': '©荒木飛呂彦/集英社・ジョジョの奇妙な冒険製作委員会', 'site': 'http://wwws.warnerbros.co.jp/jojo-animation/' },
			{ 'title': 'Kamigami no Asobi', 'credit': 'Copyright (C) BROCCOLI', 'site': 'http://kamiaso-anime.com/' },
			{ 'title': 'Kindaichi Case Files Returns', 'credit': '© Seimaru Amagi, Fumiya Sato, Kodansha/YTV, Toei Animation', 'site': 'http://www.toei-anim.co.jp/tv/kindaichi_r/index.html' },
			{ 'title': 'La Corda d\'Oro -Blue Sky-', 'credit': '© Yuki Kure, Hakusensha, KOEI Co., Ltd./Corda Production Committee', 'site': 'http://www.ntv.co.jp/corda/' },
			{ 'title': 'One Week Friends', 'credit': '©MATCHA HAZUKI/SQUARE ENIX', 'site': 'http://www.oneweekfriends.com/' },
			{ 'title': 'Riddle Story of Devil (Akuma no Riddle)', 'credit': '©高河ゆん・南方純／ＫＡＤＯＫＡＷＡ刊／「悪魔のリドル」製作委員会', 'site': 'http://akuma-riddle.com/' },
			{ 'title': 'The irregular at magic high school', 'credit': '© Tsutomu Satou / Kadokawa ASCII Media Works Publication / Mahōka Kōkō Production Committee', 'site': 'http://mahouka.us/' },
			{ 'title': 'The Kawai Complex Guide to Manors and Hostel Behavior', 'credit': '©宮原るり・少年画報社／委員会はみんな河合荘', 'site': 'http://www.tbs.co.jp/anime/kawaisou/' },
			{ 'title': 'The World is Still Beautiful', 'credit': '© Dai Shiina, Hakusensha/Ooshitsu Kaihō Magazine Editorial Department', 'site': 'http://www.ntv.co.jp/soreseka/' },
			{ 'title': 'Ai Mai Mi: Mousou Catastrophe', 'credit': '© Choboraunyopomi/Takeshobo', 'site': 'http://www.takeshobo.co.jp/sp/tv_aimaimi/' },
			{ 'title': 'Akame ga Kill!', 'credit': '© タカヒロ・田代哲也／スクウェアエニックス・「アカメが斬る！」製作委員会', 'site': 'http://akame.tv/' },
			{ 'title': 'Aldnoah.Zero', 'credit': '© Olympus Knights/Aniplex, Project AZ', 'site': 'http://www.aldnoahzerousa.com/' },
			{ 'title': 'Ao Haru Ride', 'credit': '© 2014 咲坂伊緒／集英社・「アオハライド」製作委員会', 'site': 'http://aoha-anime.com/' },
			{ 'title': 'Bakumatsu Rock', 'credit': '© 2014 Marvelous AQL', 'site': 'http://bakumatsu.marv.jp/' },
			{ 'title': 'Barakamon', 'credit': '©ヨシノサツキ／スクウェアエニックス・「ばらかもん」製作委員会', 'site': 'http://www.barakamon.jp/' },
			{ 'title': 'DRAMAtical Murder', 'credit': '© Nitroplus／DRAMAtical Murder製作委員会', 'site': 'http://dmmd-anime.com/' },
			{ 'title': 'Fate/kaleid liner Prisma☆Illya 2wei!', 'credit': '©2014 ひろやまひろし・TYPE-MOON／ＫＡＤＯＫＡＷＡ 角川書店刊／「プリズマ☆イリヤ ツヴァイ！」製作委員会', 'site': 'http://prisma-illya.jp/' },
			{ 'title': 'Free! Eternal Summer', 'credit': '© Kōji Ōji, Kyoto Animation/Iwatobi High School Swimming Club', 'site': 'http://iwatobi-sc.com/' },
			{ 'title': 'Futsuu no Joshikousei ga [Locodol] Yatte Mita.', 'credit': '©小杉光太郎・一迅社／流川市ふるさと振興課', 'site': 'http://www.tbs.co.jp/anime/locodol/' },
			{ 'title': 'Gekkan Shoujo Nozaki-kun', 'credit': '©椿いづみ／スクウェアエニックス・「月刊少女野崎くん」製作委員会', 'site': 'http://nozakikun.tv/' },
			{ 'title': 'Glasslip', 'credit': '© glasslip project', 'site': 'http://glasslip.jp/' },
			{ 'title': 'Hanamonogatari', 'credit': '© NISIOISIN/KODANSHA, ANIPLEX, SHAFT', 'site': 'http://www.monogatari-series.com/' },
			{ 'title': 'Hanayamata', 'credit': '©浜弓場 双・芳文社／ハナヤマタ製作委員会', 'site': 'http://hanayamata.com/' },
			{ 'title': 'Jinsei', 'credit': '©川岸殴魚・小学館／人生製作委員会', 'site': 'http://www.vap.co.jp/jinsei/' },
			{ 'title': 'Kuroshitsuji: Book of Circus', 'credit': '© 枢やな/スクウェアエニックス・黒執事Project・MBS', 'site': 'http://www.kuroshitsuji.tv/' },
			{ 'title': 'Love Stage!!', 'credit': '©影木栄貴 蔵王大志', 'site': 'http://lovestage-tv.jp/' },
			{ 'title': 'Majimoji Rurumo', 'credit': '© Wataru Watanabe, Kodansha/Magimoji Rurumo Production Committee', 'site': 'http://anime-rurumo.com/' },
			{ 'title': 'Minarai Diva', 'credit': '© 2014 mmbi,Inc.', 'site': 'http://minaraidiva.jp/' },
			{ 'title': 'Momo Kyun Sword', 'credit': 'Copyright© Kibidango Project All Rights Reserved.', 'site': 'http://www.momokyun.com/' },
			{ 'title': 'Nobunaga Concerto', 'credit': '© 石井あゆみ・小学館／フジテレビジョン', 'site': 'http://www.fujitv.co.jp/nobunaga-concerto-anime/' },
			{ 'title': 'Pri Para', 'credit': '©Ｔ－ＡＲＴＳ / syn Sophia / テレビ東京 / PP製作委員会', 'site': 'http://www.tv-tokyo.co.jp/anime/pripara/' },
			{ 'title': 'RAIL WARS!', 'credit': '©豊田 巧/創芸社・ProjectRW!', 'site': 'http://www.groundnet.co.jp/railwars/index.html' },
			{ 'title': 'Re:␣Hamatora', 'credit': '© Café Nowhere/Hamatora Production Committee', 'site': 'http://hamatorapj.com/reply/index.php' },
			{ 'title': 'Rokujouma no Shinryakusha!?', 'credit': '©健速・HobbyJAPAN／ころな荘管理組合', 'site': 'http://www.hobbyjapan.co.jp/rokujoma/' },
			{ 'title': 'Sabagebu!', 'credit': '© 松本ひで吉・講談社／「さばげぶっ！」製作委員会', 'site': 'http://sabagebu.com/' },
			{ 'title': 'Seirei Tsukai no Blade Dance', 'credit': '©2014 志瑞祐・株式会社KADOKAWA メディアファクトリー刊／精霊使いの剣舞製作委員会', 'site': 'http://www.bladedance.tv/' },
			{ 'title': 'Sengoku Basara: End of Judgement', 'credit': '© CAPCOM/BASARA JE', 'site': 'http://www.ntv.co.jp/basara_je/' },
			{ 'title': 'Shirogane no Ishi: Argevollen', 'credit': '©AIOS/PROJECT ARGEVOLLEN', 'site': 'http://argevollen.com/index.html' },
			{ 'title': 'Space☆Dandy', 'credit': '© Project SPACE DANDY', 'site': 'http://www.space-dandy.com/' },
			{ 'title': 'Sword Art Online', 'credit': '©2014 Reki Kawahara / KADOKAWA / ASCII Media Works / SAO II Project', 'site': 'http://www.swordart-online.net/' },
			{ 'title': 'Tokyo ESP', 'credit': '©2014 瀬川はじめ／KADOKAWA角川書店刊／[東京ESP]製作委員会', 'site': 'http://www.tokyo-esp.org/' },
			{ 'title': 'Tokyo Ghoul', 'credit': '©石田スイ／集英社・東京喰種製作委員会', 'site': 'http://www.marv.jp/special/tokyoghoul' },
			{ 'title': 'Yama no Susume', 'credit': '©しろ / アース・スター エンターテイメント', 'site': 'http://yamanosusume.com/' },
			{ 'title': 'Zankyou no Terror', 'credit': '©TERROR IN RESONANCE Committee', 'site': 'http://terror-in-tokyo.com/' },
			{ 'title': 'Kyoukai no Kanata', 'credit': '© Kyoto Animation', 'site': 'http://tv.anime-kyokai.com/' },
			{ 'title': 'Yuru Yuri', 'credit': '© Ichijinsha / Dogakobo', 'site': 'http://www.yuruyuri.com/' },
			{ 'title': 'Yuru Yuri 3', 'credit': '© Ichijinsha / TYO Animations', 'site': 'http://www.yuruyuri.com/' },
			{ 'title': 'CLANNAD', 'credit': '©Visual Art\'s/Key/hikarisaka High School Drama Club', 'site': 'http://www.tbs.co.jp/clannad/clannad1/' },
			{ 'title': 'Tamako Market', 'credit': '© Kyoto Animation', 'site': 'http://tamakomarket.com/' },
			{ 'title': 'Future Card Buddyfight', 'credit': '© 相棒学園／テレビ愛知', 'site': 'http://www.tv-aichi.co.jp/fc-buddyfight/' },
			{ 'title': 'Gin no Saji', 'credit': '© 荒川弘・小学館／エゾノー祭実行委員会', 'site': 'http://www.ginsaji-anime.com/' },
			{ 'title': 'HappinessCharge Precure!', 'credit': '©ABC・東映アニメーション', 'site': 'http://www.toei-anim.co.jp/tv/happinesscharge_precure/' },
			{ 'title': 'Inari, Kon Kon, Koi Iroha', 'credit': '© 2014 よしだもろへ／KADOKAWA 角川書店刊／いなり製作委員会 / © 京都府 まゆまろ 13176 / © 2013 City of Kyoto. All rights reserved.', 'site': 'http://inarikonkon.jp/' },
			{ 'title': 'Maken-ki Two', 'credit': '© 2013 Hiromitsu Takeda/PUBLISHED BY KADOKAWA Fujimishobo/MAKEN-KI TWO Partners', 'site': 'http://maken-ki-two.com/' },
			{ 'title': 'Mikakunin DE Shinkoukei', 'credit': '© 荒井チェリー／一迅社・未確認で進行形製作委員会', 'site': 'http://mikakunin.jp/' },
			{ 'title': 'Nisekoi', 'credit': '© 古味直志／集英社・アニプレックス・シャフト・ＭＢＳ', 'site': 'http://www.nisekoiusa.com/' },
			{ 'title': 'Nobunagun', 'credit': '© 久正人 ／アース・スター エンターテイメント・「ノブナガン製作委員会」', 'site': 'http://www.vap.co.jp/nobunagun/' },
			{ 'title': 'Noragami', 'credit': '© Adachitoka/Kodansha/Noragami Production Committee', 'site': 'http://noragami-anime.net/' },
			{ 'title': 'No-rin', 'credit': '© 2014 白鳥士郎・SBクリエイティブ／のうりんプロジェクト', 'site': 'http://www.no-rin.tv/' },
			{ 'title': 'Saikin, Imouto no Yousu ga Chotto Okashiinda ga.', 'credit': '© Mari Matsuzawa, Kadokawa Fujimi Shobo/ImoCho. Production Committee', 'site': 'http://imocyo-anime.com/' },
			{ 'title': 'Saki: Zenkoku-hen', 'credit': '© 小林 立/スクウェアエニックス・咲全国編製作委員会', 'site': 'http://www.saki-anime.com/' },
			{ 'title': 'Buddy Complex', 'credit': '©SUNRISE/BUDDY COMPLEX COMMITTEE', 'site': 'http://buddy-complex.jp/' },
			{ 'title': 'Chuunibyou demo Koi ga Shitai!', 'credit': '© 虎虎／京都アニメーション／中二病でも製作委員会', 'site': 'http://www.anime-chu-2.com/' },
			{ 'title': 'D-Frag!', 'credit': '© Tomoya Haruno/PUBLISHED BY KADOKAWA CORPORATION MEDIAFACTORY/D-Fragments Project', 'site': 'http://www.d-fragments.net/' },
			{ 'title': 'Hamatora', 'credit': '© カフェノーウェア/ハマトラ製作委員会', 'site': 'http://hamatorapj.com/' },
			{ 'title': 'Magical Warfare', 'credit': '© スズキヒサシ／株式会社KADOKAWA　メディアファクトリー刊／すばる魔法学院', 'site': 'http://www.tbs.co.jp/anime/mahosen/' },
			{ 'title': 'Nobunaga the Fool', 'credit': '© 河森正治・サテライト／ALC／GP／ノブナガ・ザ・フール製作委員会', 'site': 'http://www.nobunaga.tv/' },
			{ 'title': 'Sakura Trick', 'credit': '© タチ・芳文社／桜Trick製作委員会', 'site': 'http://www.tbs.co.jp/anime/sakura' },
			{ 'title': 'Seitokai Yakuindomo', 'credit': '© 氏家ト全・講談社/桜才学園生徒会新室', 'site': 'http://www.starchild.co.jp/special/seitokai/' },
			{ 'title': 'Sekai Seifuku: Bouryaku no Zvezda', 'credit': '© hunting cap brothers/Aniplex,Project ZP', 'site': 'http://www.sekaiseifuku-zzz.com/' },
			{ 'title': 'Super Sonico the Animation', 'credit': '© Nitroplus/そにアニProject', 'site': 'http://soniani.jp/' },
			{ 'title': 'Toaru Hikūshi e no Koiuta', 'credit': '© Koroku Inumura, Shogakukan/Toaru Hikūshi e no Koiuta Project', 'site': 'http://koiuta.tv/' },
			{ 'title': 'Wake Up, Girls!', 'credit': '© Green Leaves / Wake Up, Girls!', 'site': 'http://wakeupgirls.jp/' },
			{ 'title': 'Witch Craft Works', 'credit': '© 水薙竜・講談社／ウィッチクラフトワークス製作委員会', 'site': 'http://www.witch-cw-anime.jp/' },
			{ 'title': 'Wizard Barristers - Benmashi Cecil', 'credit': '© WIZARD BARRISTERS PARTNERS', 'site': 'http://wizardbarristers.com/' },
			{ 'title': 'Shin Sekai Yori', 'credit': '©2012 K・K/S', 'site': 'http://www.tv-asahi.co.jp/shinsekaiyori/' },
			{ 'title': 'DEVIL SURVIVOR2 the ANIMATION', 'credit': '©index/DS2A', 'site': 'http://ds2a.jp/' },
			{ 'title': 'Z/X Ignition', 'credit': '© Z/X IGNITION製作委員会', 'site': 'http://zxignition.tv/' },
			{ 'title': 'Ameiro Cocoa: Rainy Color e Youkoso!', 'credit': '© ＩＡＭ電子出版／雨色ココア製作委員会 All Rights Reserved.', 'site': 'http://rainycocoa.jp/index.html' },
			{ 'title': 'Anitore! EX', 'credit': '© 6pack/あにトレ！EX製作委員会', 'site': 'http://anime-training.com/' },
			{ 'title': 'Brave Beats', 'credit': '© BNP/ブレイブビーツ製作委員会, メ〜テレ 注意：内容および画像の転載はお断りいたします。お問い合せ先はこちらをご覧ください。', 'site': 'http://bravebeats.net/' },
			{ 'title': 'Comet Lucifer', 'credit': '© Project Felia／「コメット・ルシファー」製作委員会', 'site': 'http://comet-lucifer.jp/' },
			{ 'title': 'Concrete Revolutio: Choujin Gensou', 'credit': '© BONES・會川 昇／コンクリートレボルティオ製作委員会', 'site': 'http://www.concreterevolutio.com/' },
			{ 'title': 'Dance with Devils', 'credit': '© グリモワール編纂室／Dance with Devils製作委員会', 'site': 'http://dwd-anime.com/' },
			{ 'title': 'DD Hokuto no Ken 2: Ichigo Aji+', 'credit': '© 武論尊・原哲夫／NSP1983，© イチゴ味2015', 'site': 'http://www.hikanukobinukaeriminuteiounitousouhanainodaaaaa.com/' },
			{ 'title': 'Diabolik Lovers More, Blood', 'credit': '© Rejet・IDEA FACTORY／DIABOLIK LOVERS MB PROJECT', 'site': 'http://anime-dialover.com/dlmb/' },
			{ 'title': 'Dochamon Junior', 'credit': '', 'site': 'http://www9.nhk.or.jp/anime/dochamon/' },
			{ 'title': 'Doushitemo Eto ni Hairitai', 'credit': '© Pollyanna Graphics INC. © BAKETAN BLOG All Rights Reserved.', 'site': 'http://etononeko.jp/' },
			{ 'title': 'Fushigi na Somera-chan', 'credit': 'copyright  ©   ちょぼらうにょぽみ/一迅社・野乃本魔法拳道場2015', 'site': 'http://dreamcreation.co.jp/somera/' },
			{ 'title': 'Fuusen Inu Tinny 2nd Season', 'credit': '© 2014 Genki Kawamura & Kenjiro Sano / Tinny Project', 'site': 'http://www9.nhk.or.jp/anime/tinny/' },
			{ 'title': 'Gakusen Toshi Asterisk', 'credit': '© 2015 三屋咲ゆう・株式会社KADOKAWA／アスタリスク製作委員会', 'site': 'http://asterisk-war.com/' },
			{ 'title': 'Garo: Guren no Tsuki', 'credit': '© 2015「紅蓮ノ月」 雨宮慶太 / 東北新社', 'site': 'http://garo-project.jp/ANIME2/' },
			{ 'title': 'Gochuumon wa Usagi Desu ka??', 'credit': '© Koi・芳文社／ご注文は製作委員会ですか？？', 'site': 'http://www.gochiusa.com/' },
			{ 'title': 'Hacka Doll the Animation', 'credit': '© DeNA／ハッカドール THE あにめ～しょん製作委員会', 'site': 'http://hackadoll-anime.com/' },
			{ 'title': 'Haikyuu!! Second Season', 'credit': '© 古舘春一／集英社・「ハイキュー!! セカンドシーズン」製作委員会・MBS', 'site': 'http://www.j-haikyu.com/anime/index.html' },
			{ 'title': 'Heavy Object', 'credit': '© 2015 鎌池和馬／ＫＡＤＯＫＡＷＡ　アスキー・メディアワークス刊／PROJECT HO', 'site': 'http://heavyobject.net/' },
			{ 'title': 'Hidan no Aria AA', 'credit': '© 2015 赤松中学・KADOKAWA刊 / ProjectAA', 'site': 'http://www.tbs.co.jp/anime/aria/' },
			{ 'title': 'High School Star Musical', 'credit': '© ひなた凛／スタミュ製作委員会', 'site': 'http://hstar-mu.com/index.html' },
			{ 'title': 'Itoshi no Muco', 'credit': '© みずしな孝之・講談社/いとしのムーコ製作委員会', 'site': 'http://www.anime-muco.com/' },
			{ 'title': 'JK-Meshi!', 'credit': '(C)「JKめし！」製作委員会', 'site': 'http://www.jkmeshi.jp/' },
			{ 'title': 'K: Return of Kings', 'credit': '© GoRA・GoHands／k-project　© Copyright King Record.Co.,Ltd. All Rights Reserved.', 'site': 'http://k-project-come-back.jpn.com/' },
			{ 'title': 'Kagewani', 'credit': '© Copyright Tomovies,LLC / DIRECTIONS,Inc', 'site': 'http://kagewani.com/' },
			{ 'title': 'Kamisama Minarai: Himitsu no Cocotama', 'credit': 'Copyright© BANDAI Co.LTD. All Rights Reserved. / © BANDAI/TV TOKYO・ここたま製作委員会', 'site': 'http://www.coco-tama.com/' },
			{ 'title': 'Ketsuekigata-kun! 3rd Season', 'credit': '© LEEONSMART / アース・スター エンターテイメント / 血液型くん! 製作委員会', 'site': 'http://ketsuekigatakun.com/' },
			{ 'title': 'Komori-san wa Kotowarenai!', 'credit': '', 'site': 'http://komori-anime.com/' },
			{ 'title': 'Kowabon', 'credit': '', 'site': 'http://www.kbc.co.jp/kowabon/' },
			{ 'title': 'Kyoufu! Zombie Neko', 'credit': '© kanahei / TXCOM / ZNP', 'site': '#' },
			{ 'title': 'Lance N\' Masques', 'credit': '© 子安秀明/ポニーキャニオン・ProjectLNM', 'site': 'http://lanceandmasques.us/' },
			{ 'title': 'Rokka -Braves of the Six Flowers', 'credit': '© Ishio Yamagata / SHUEISHA, Project ROKKA', 'site': 'http://rokka-anime.us/' },
			{ 'title': 'Lupin III - L\'avventura Italiana', 'credit': '原作 : モンキー・パンチ © TMS', 'site': 'http://lupin-new-season.jp/' },
			{ 'title': 'Etotama', 'credit': '© ETO ', 'site': 'http://etotama.us/' },
			{ 'title': 'Sound! Euphonium', 'credit': '©Ayano Takeda, TAKARAJIMASHA/Hibike Partners', 'site': 'http://anime-eupho.us/' },
			{ 'title': 'Miss Monochrome: The Animation', 'credit': '© Miss Monochrome Committee', 'site': 'http://www.tv-tokyo.co.jp/anime/miss_monochrome/index2.html' },
			{ 'title': 'Neko Nanka Yondemo Konai.', 'credit': '(c)杉作/実業之日本社', 'site': '#' },
			{ 'title': 'Neko no Dayan: Nihon e Iku', 'credit': '©Akiko Ikeda/Project Dayan', 'site': 'http://anime-dayan.com/' },
			{ 'title': 'Noragami Aragoto', 'credit': '© あだちとか・講談社 / ノラガミ ARAGOTO製作委員会', 'site': 'http://noragami-anime.net/' },
			{ 'title': 'One Punch Man', 'credit': '© ONE・村田雄介／集英社・ヒーロー協会本部', 'site': 'http://onepunchman-anime.net/' },
			{ 'title': 'Onsen Yousei Hakone-chan', 'credit': 'Copyright © 2015 由伊大輔/COMICメテオ/ハコネちゃん製作委員会', 'site': 'http://www.hakone-chan.jp/' },
			{ 'title': 'Ore ga Ojou-sama Gakkou ni "Shomin Sample" Toshite Gets♥Sareta Ken', 'credit': '© 七月隆文・閏月戈・一迅社／清華院桜藤会 ', 'site': 'http://syominsample-anime.jp/' },
			{ 'title': 'Oshiri Kajiri Mushi 4', 'credit': '', 'site': 'http://www9.nhk.or.jp/anime/oshiri/2nd/' },
			{ 'title': 'Osomatsu-san', 'credit': '© 赤塚不二夫／おそ松さん製作委員会', 'site': 'http://osomatsusan.com/' },
			{ 'title': 'Owari no Seraph: Nagoya Kessen-hen', 'credit': '© 鏡貴也・山本ヤマト・降矢大輔／集英社・終わりのセラフ製作委員会　© Takaya Kagami, Yamato Yamamoto, Daisuke Furuya/SHUEISHA, Seraph of the End Project', 'site': 'http://owarino-seraph.jp/' },
			{ 'title': 'Owarimonogatari', 'credit': '© 西尾維新／講談社・アニプレックス・シャフト', 'site': 'http://www.monogatari-series.com/owarimonogatari/' },
			{ 'title': 'Peeping Life TV: Season 1??', 'credit': '©NTV/Tatsunoko/Tezuka/CoMix Wave/NTVM', 'site': 'http://www.ntv.co.jp/pltv/' },
			{ 'title': 'Pokémon XY&Z', 'credit': '© Nintendo・Creatures・GAME FREAK・TV Tokyo・ShoPro・JR Kikaku © Pokémon', 'site': 'http://www.tv-tokyo.co.jp/anime/pokemon_xyz/index2.html' },
			{ 'title': 'Rakudai Kishi no Cavalry', 'credit': '© 海空りく・SBクリエイティブ／落第騎士の英雄譚製作委員会', 'site': 'http://www.ittoshura.com/' },
			{ 'title': 'Sakurako-san no Ashimoto ni wa Shitai ga Umatteiru', 'credit': '© 2015 太田紫織／KADOKAWA／櫻子さん製作委員会', 'site': 'http://sakurakosan.jp/' },
			{ 'title': 'Shin Atashinchi', 'credit': '© ママレード/KADOKAWA・シンエイ・ADK', 'site': 'http://www.animax.co.jp/special/atashinchi/' },
			{ 'title': 'Shingeki! Kyojin Chuugakkou', 'credit': '© 中川沙樹・諫山創・講談社／「進撃！巨人中学校」製作委員会', 'site': 'http://kyojinchu.tv/' },
			{ 'title': 'Soukyuu no Fafner: Dead Aggressor - Exodus', 'credit': '© XEBEC・FAFNER EXODUS PROJECT ｜ © Copyright King Record.Co.,Ltd. All Right Reserved.', 'site': 'http://www.fafner-exodus.jp/' },
			{ 'title': 'Subete ga F ni Naru: The Perfect Insider', 'credit': '© 森博嗣・講談社/「すべてがFになる」製作委員会', 'site': 'http://www.f-noitamina.com/' },
			{ 'title': 'Taimadou Gakuen 35 Shiken Shoutai', 'credit': '© 2015 柳実冬貴・切符／ＫＡＤＯＫＡＷＡ／対魔導学園35製作委員会', 'site': 'http://35shoutai.jp/' },
			{ 'title': 'Tantei Team KZ Jiken Note', 'credit': 'Copyright © 2012-2015 SIGNAL.MD. All rights reserved.', 'site': 'http://www9.nhk.or.jp/anime/kz/' },
			{ 'title': 'Teekyuu', 'credit': '© ルーツ / Piyo / アース・スター エンターテイメント / 亀井戸高校テニス部', 'site': 'http://te-kyu.com/' },
			{ 'title': 'Utawarerumono: Itsuwari no Kamen', 'credit': '© うたわれるもの偽りの仮面製作委員会', 'site': 'http://utawarerumono.jp/' },
			{ 'title': 'Valkyrie Drive: Mermaid', 'credit': '© VALKYRIE DRIVE PARTNERS', 'site': 'http://valkyriedrive.jp/anime/' },
			{ 'title': 'Young Black Jack', 'credit': '© ヤング ブラック・ジャック製作委員会', 'site': 'http://www.tbs.co.jp/anime/ybj/' },
			{ 'title': 'Yuru Yuri Nachuyachumi!+', 'credit': '© なもり/一迅社・七森中ごらく部', 'site': 'http://www.yuruyuri.com/' },
			{ 'title': 'Yuru Yuri San☆Hai!', 'credit': '© 2015 なもり/一迅社・七森中ごらく部', 'site': 'http://www.yuruyuri.com/' },
			{ 'title': 'Ansatsu Kyoushitsu', 'credit': '(c)松井優征 / 集英社・アニメ「暗殺教室」製作委員会', 'site': 'http://www.ansatsu-anime.com/' },
			{ 'title': 'Binan Koukou Chikyuu Bouei-bu Love!', 'credit': '©Kurari Umatani/KUROTAMAYU', 'site': 'http://boueibu.com/us/index.html' },
			{ 'title': 'Death Parade', 'credit': '©立川譲／「デス・パレード」製作委員会', 'site': 'http://www.deathparade.jp/' },
			{ 'title': 'Doamaiger D', 'credit': '©甘匠堂', 'site': 'http://www.tvk-yokohama.com/doamai/' },
			{ 'title': 'Dog Days″', 'credit': '© PROJECT DD3', 'site': 'http://www.dogdays.tv/' },
			{ 'title': 'Durarara!! x2 Shou', 'credit': 'Copyright 成田良悟／ＫＡＤＯＫＡＷＡ アスキー・メディアワークス刊／池袋ダラーズ', 'site': 'http://www.durarara.com/' },
			{ 'title': 'Go! Princess Precure', 'credit': '©ABC・東映アニメーション', 'site': 'http://www.toei-anim.co.jp/tv/princess_precure/' },
			{ 'title': 'Isuca', 'credit': '©2014 高橋脩／KADOKAWA 角川書店刊／「ISUCA-イスカ-」製作委員会', 'site': 'http://isuca.net/' },
			{ 'title': 'Junketsu no Maria', 'credit': '©石川雅之・講談社／純潔のマリア製作委員会', 'site': 'http://junketsu-maria.tv/' },
			{ 'title': 'Juuou Mujin no Fafnir', 'credit': '©ツカサ／講談社 イラスト：梱枝りこ', 'site': 'http://cont.lanove.kodansha.co.jp/9906/21524.html' },
			{ 'title': 'Kamisama Hajimemashita◎', 'credit': '© Julietta Suzuki / Hakusensha-Kamisama Kiss Project. Julietta Suzuki / Hakusensha-Kamisama Kiss 2 Project All Rights Reserved. ', 'site': 'http://www.tv-tokyo.co.jp/anime/kamisama/index2.html' },
			{ 'title': 'Kantai Collection: KanColle', 'credit': '©2014 「艦これ」連合艦隊司令部', 'site': 'http://kancolle-anime.jp/' },
			{ 'title': 'Koufuku Graffiti', 'credit': '©川井マコト・芳文社／幸腹グラフィティ製作委員会©', 'site': 'http://www.tbs.co.jp/anime/koufuku_g/' },
			{ 'title': 'Kuroko\'s Basketball Season 3', 'credit': '©Tadatoshi Fujimaki/SHUEISHA, Team Kuroko', 'site': 'http://www.kurobas.com/' },
			{ 'title': 'Military!', 'credit': '©まもウィリアムズ/一迅社・クラコウジア公国軍極東部隊 2015', 'site': 'http://dreamcreation.co.jp/militari/' },
			{ 'title': 'Rolling☆Girls', 'credit': '© 2015 “The Rolling Girls” Production Committee', 'site': 'http://rollinggirls.com/' },
			{ 'title': 'Saenai Heroine no Sodatekata', 'credit': '(C)2015 丸戸史明・深崎暮人・KADOKAWA 富士見書房／冴えない製作委員会', 'site': 'http://www.saekano.com/' },
			{ 'title': 'Seiken Tsukai no World Break', 'credit': '©あわむら赤光・SBクリエイティブ/ワルブレ製作委員会', 'site': 'http://warubure-anime.com/' },
			{ 'title': 'Sengoku Musou', 'credit': '(C)コーエーテクモゲームス/アニメ戦国無双製作委員会', 'site': 'http://www.tv-tokyo.co.jp/anime/sengokumusou/index2.html' },
			{ 'title': 'Shinmai Maou no Testament', 'credit': '©2015 上栖 綴人・Nitroplus ／ KADOKAWA　角川書店刊／「新妹魔王の契約者」製作委員会', 'site': 'http://anime-shinmaimaou.com/' },
			{ 'title': 'Shounen Hollywood: Holly Stage for 50', 'credit': '© Noel Japan Agency', 'site': 'http://anime-shinmaimaou.com/' },
			{ 'title': 'Tantei Kageki Milky Holmes TD', 'credit': '©ミルキィTD製作委員会', 'site': 'http://milky-holmes.com/' },
			{ 'title': 'The IDOLM@STER: Cinderella Girls', 'credit': '©BNGI / PROJECT CINDERELLA', 'site': 'http://imas-cinderella.com/' },
			{ 'title': 'Tokyo Ghoul √A', 'credit': '© Sui Ishida/Shueisha, Tokyo Ghoul Production Committee', 'site': 'http://www.marv.jp/special/tokyoghoul' },
			{ 'title': 'Tsukimonogatari: Yotsugi Doll', 'credit': '©西尾維新／講談社・アニプレックス・シャフト', 'site': 'http://www.monogatari-series.com/tsukimonogatari/' },
			{ 'title': 'Yoru no Yatterman', 'credit': '©タツノコプロ・夜ノヤッターマン製作委員会 2015', 'site': 'http://yatterman.jp/' },
			{ 'title': 'Yuri Kuma Arashi', 'credit': '（C）2015 イク二ゴマモナカ/ユリクマ二クル', 'site': 'http://yurikuma.jp/' },
			{ 'title': 'Puella Magi Madoka Magica', 'credit': '©Magica Quartet / Aniplex・Madoka Partners・MBS', 'site': 'http://www.madoka-magica.com/' },
			{ 'title': 'Senki Zesshou Symphogear', 'credit': '©Project シンフォギア', 'site': 'http://symphogear.com' },
			{ 'title': 'Bikini Warriors', 'credit': '©HOBBY JAPAN', 'site': 'http://bikini-warriors.com/anime/' },
			{ 'title': 'Persona 4 the Golden ANIMATION', 'credit': '©ATLUS (C)SEGA/P4GA Committee', 'site': 'http://www.p4ga.jp/' },
			{ 'title': 'SUSHI NINJA', 'credit': '©GENCO', 'site': 'http://www.sushininja.jp/' },
			{ 'title': 'THE IDOLM@STER', 'credit': '©BNEI／PROJECT iM@S', 'site': 'http://www.idolmaster-anime.jp/tv/index2.html' },
			{ 'title': 'M3 the dark metal', 'credit': ' ©Junichi Sato, Mari Okada, Satelight/M3 PROJECT', 'site': 'http://www.m3-project.com/' },
			{ 'title': 'KILL la KILL', 'credit': '©TRIGGER, Kazuki Nakashima/Kill la Kill Partnership', 'site': 'http://www.killlakill.com/' },
			{ 'title': 'GOD EATER', 'credit': '©BNEI / PROJECT G.E.', 'site': 'http://anime.godeater.jp' },
			{ 'title': 'Attack on Titan', 'credit': '©HK/AOT', 'site': 'http://shingeki.tv' },
			{ 'title': 'Classroom Crisis', 'credit': '©2015 CC PROJECT', 'site': 'http://www.classroomcrisis.com/' },
			{ 'title': 'LoveLive! School idol project', 'credit': '©2013 PROJECT LoveLive!', 'site': 'http://www.lovelive-anime.jp/' },
			{ 'title': 'WORKING!!3', 'credit': '©Karino Takatsu/SQUARE ENIX, "WORKING!!3" Project', 'site': 'http://www.wagnaria.com/' },
			{ 'title': 'Gunslinger Stratos', 'credit': '©2015 SQUARE ENIX/GUNS PROJECT', 'site': 'http://www.guns-project.jp/' },
			{ 'title': 'Everyday Life with Monster Girls', 'credit': '©2015 OKAYADO/TOKUMA SHOTEN・MONMUSU PARTNERS All Rights Reserved.', 'site': 'http://monmusu.tv/' },
			{ 'title': 'Blood Blockade Battlefront', 'credit': '©2015 Yasuhiro Nightow/Shueisha,Blood Blockade Battlefront Project', 'site': 'http://kekkaisensen.com/' },
			{ 'title': 'Kanon', 'credit': '©VisualArt\'s/Key/Hyakkaya', 'site': 'http://www.tbs.co.jp/anime/kanon/' },
			{ 'title': 'Air', 'credit': '©VisualArt\'s/Key/Angel Seekers', 'site': 'http://www.tbs.co.jp/anime/air/' },
			{ 'title': 'Mai-HiME', 'credit': '© SUNRISE', 'site': 'http://my-zhime.net/hime/index.html' },
			{ 'title': 'Mai Otome', 'credit': '© SUNRISE', 'site': 'http://my-zhime.net/tv/index.html' },
			{ 'title': 'Yamada-kun and the Seven Witches', 'credit': '©古河美希・講談社', 'site': 'http://www.yamajo-anime.com/' },
			{ 'title': 'The Heroic Legend of Arslan', 'credit': '©2015 荒川弘・田中芳樹・講談社／「アルスラーン戦記」製作委員会・MBS', 'site': 'http://www.arslan.jp/' },
			{ 'title': 'Aku no Hana', 'credit': '©Shuzo Ozhimi・Kodansha / Akunohana Committee', 'site': 'http://akunohana-anime.jp/' },
			{ 'title': 'Kids on the Slope', 'credit': '©Yuki Kodama, Shogakukan / KIDS ON THE SLOPE Committee', 'site': 'http://www.noitamina-apollon.com/' },
			{ 'title': 'Mawaru Penguindrum', 'credit': '©ikunichawder/pingroup', 'site': 'http://penguindrum.jp/' },
			{ 'title': '"Arpeggio of Blue Steel -Ars Nova Cadenza-"', 'credit': '© Ark Performance/Shonen Gahosha/Arpeggio Partners', 'site': 'http://aokihagane.com/' },
			{ 'title': 'Ace of Diamond', 'credit': '©寺嶋裕二・講談社／「ダイヤのＡ‐ＳＳ‐」製作委員会・テレビ東京', 'site': 'http://diaace.com/' },
			{ 'title': 'Gunparade March', 'credit': '（Ｃ）ＳＣＥＩ・ＰｒｏｊｅｃｔＧＰＭ', 'site': 'http://www.jcstaff.co.jp/sho-sai/gpm-shokai/gpm-index.htm' },
			{ 'title': 'Innocent Venus', 'credit': '（Ｃ）INNOCENT PROJECT／バンダイビジュアル', 'site': 'http://www.innocent-v.com/' },
			{ 'title': 'Baccano!', 'credit': '©東村アキコ・講談社／海月姫製作委員会', 'site': 'http://kuragehime.noitamina.tv/' },
			{ 'title': 'Kamisama Dolls', 'credit': '©2011 やまむらはじめ・小学館／案山子保存協会・テレビ東京', 'site': 'http://kamisama-anime.jp/' },
			{ 'title': 'Sengoku Collection', 'credit': '©Konami Digital Entertainment, NAS/「戦国コレクション」製作委員会', 'site': 'http://www.tv-tokyo.co.jp/anime/sencolle/index2.html' },
			{ 'title': 'Princess Jellyfish', 'credit': '', 'site': 'http://www.baccano.jp/' },
			{ 'title': 'Kamichu!', 'credit': '©ベサメムーチョ/アニプレックス', 'site': 'http://www.sonymusic.co.jp/Animation/kamichu/' },
			{ 'title': 'My Teen Romantic Comedy SNAFU', 'credit': '©渡 航、小学館／やはりこの製作委員会はまちがっている。続', 'site': 'http://www.tbs.co.jp/anime/oregairu/' },
			{ 'title': 'Garakowa -Restore the World-', 'credit': '©Project D. backup', 'site': 'http://garakowa.us/' },
			{ 'title': 'Natsume\'s Book of Friends', 'credit': '©緑川ゆき・白泉社／「夏目友人帳」製作委員会', 'site': 'http://www.natsume-anime.jp/' },
			{ 'title': 'Rin-ne', 'credit': '©高橋留美子・小学館／NHK・NEP・ShoPro', 'site': 'http://www9.nhk.or.jp/anime/rinne/' },
			{ 'title': 'Kenichi: The Mightiest Disciple', 'credit': '松江名俊・小学館/ケンイチ製作委員会・テレビ東京', 'site': 'http://www.tms-e.com/tv_movie/kenichi/index.html' },
			{ 'title': 'Ojamajo Doremi', 'credit': '© ABC・東映アニメーション', 'site': 'http://www.toei-anim.co.jp/tv/doremi' },
			{ 'title': 'Bakuman.', 'credit': '©大場つぐみ・小畑健・集英社／NHK・NEP・ShoPro', 'site': 'http://www9.nhk.or.jp/anime/bakuman/' },
			{ 'title': 'Aoharu x Machinegun', 'credit': '©NAOE/スクウェアエニックス・青春×機関銃製作委員会', 'site': 'http://www.tbs.co.jp/anime/aoharu/' },
			{ 'title': 'Gangsta.', 'credit': '© Kohske/SHINCHOSHA・GANGSTA. COMMITTEE', 'site': 'http://gangsta-project.com/' },
			{ 'title': 'Deban Desu yo! Onigirizu', 'credit': 'Copyright(c)2010 NIKKATSU CORPORATION. ALL RIGHTS RESERVED.', 'site': 'http://www.necoweb.com/neco/program/detail.php?id=3201' },
			{ 'title': 'Okusama ga Seito Kaichou!', 'credit': 'copyright © 中田ゆみ／一迅社・星風高校風紀委員会2015', 'site': 'http://www.dreamcreation.co.jp/okusama/' },
			{ 'title': 'Chaos Dragon: Sekiryuu Seneki', 'credit': '©混沌計画／「ケイオスドラゴン赤竜戦役」 製作委員会', 'site': 'http://chaosdragon.red/' },
			{ 'title': 'Aquarion Logos', 'credit': '©2015 SHOJI KAWAMORI,SATELIGHT/Project AQUARION LOGOS', 'site': 'http://aqlogos.com/' },
			{ 'title': 'Ranpo Kitan: Game of Laplace', 'credit': '©乱歩奇譚倶楽部', 'site': 'http://www.rampokitan.com/' },
			{ 'title': 'Joukamachi no Dandelion', 'credit': '©春日 歩・芳文社／城下町のダンデライオン製作委員会', 'site': 'http://www.tbs.co.jp/anime/dande/' },
			{ 'title': 'Ushio to Tora (TV)', 'credit': '© 藤田和日郎・小学館／うしおととら製作委員会', 'site': 'http://ushitora.tv/' },
			{ 'title': 'Wooser no Sono Higurashi: Mugen-hen', 'credit': '©Project wooser 3', 'site': 'http://wooser.tv/' },
			{ 'title': 'Wakaba*Girl', 'credit': '©原悠衣・芳文社／白詰女子高一年藤組', 'site': 'http://wakabagirl.com/' },
			{ 'title': 'Gate: Jieitai Kanochi nite, Kaku Tatakaeri', 'credit': 'この番組はフィクションであり、登場する人物、団体、場所、事件等は実在のものとは一切関係ありません。c柳内たくみ・アルファポリス/ゲート製作委員会', 'site': 'http://gate-anime.com/' },
			{ 'title': 'Shimoneta to Iu Gainen ga Sonzai Shinai Taikutsu na Sekai', 'credit': '©赤城大空・小学館／SOX', 'site': 'http://www.shimoseka.com/' },
			{ 'title': 'Charlotte', 'credit': '(C)Visual Art\'s/Key/Charlotte Project', 'site': 'http://charlotte-anime.jp/' },
			{ 'title': 'Kurayami Santa', 'credit': '©', 'site': 'http://www.kbc.co.jp/santa/' },
			{ 'title': 'Gatchaman Crowds Insight', 'credit': '©TP/GCIP', 'site': 'http://www.ntv.co.jp/GC_insight/' },
			{ 'title': 'Dragon Ball Super', 'credit': '© バードスタジオ/集英社・フジテレビ・東映アニメーション', 'site': 'http://www.toei-anim.co.jp/tv/dragon_s/' },
			{ 'title': 'Wakako-zake', 'credit': 'Ⓒ新久千映/NSP 2011,Ⓒアニメ『ワカコ酒』製作委員会', 'site': 'http://www.wakakozake.jp/' },
			{ 'title': 'Q Transformers: Saranaru Ninki Mono e no Michi', 'credit': '©TOMY／©キュートランスフォーマープロジェクトⅡ', 'site': 'http://www.qtransformers.com/' },
			{ 'title': 'Akagami no Shirayuki-hime', 'credit': '©あきづき空太・白泉社 ／「赤髪の白雪姫」製作委員会', 'site': 'http://www.clarines-kingdom.com/' },
			{ 'title': 'To LOVE-Ru Darkness 2nd', 'credit': '©矢吹健太朗・長谷見沙貴／集英社・とらぶるダークネス製作委員会', 'site': 'http://www.j-toloveru.com/' },
			{ 'title': 'Million Doll', 'credit': '（C）Ai/COMICSMART INC./"milliondoll" Committee', 'site': 'http://milliondoll.com/' },
			{ 'title': 'Jitsu wa Watashi wa', 'credit': '©増田英二（週刊少年チャンピオン）／じつわた製作委員会', 'site': 'http://jitsuwata.tv/' },
			{ 'title': 'Non Non Biyori Repeat', 'credit': '©2015 あっと・KADOKAWA刊/旭丘分校管理組合二期', 'site': 'http://www.nonnontv.com/' },
			{ 'title': 'Kaijuu Sakaba Kanpai!', 'credit': '©怪獣酒場 カンパーイ！製作委員会', 'site': 'http://www.kaijusakabakanpai.com/' },
			{ 'title': 'Overlord', 'credit': '© 丸山くがね・KADOKAWA刊／オーバーロード製作委員会', 'site': 'http://overlord-anime.com/' },
			{ 'title': 'Sore ga Seiyuu!', 'credit': '©あさのますみ・畑健二郎／イヤホンズ応援団', 'site': 'http://soregaseiyu.com/' },
			{ 'title': 'Suzakinishi The Animation', 'credit': '©洲崎西 シーサイド・コミュニケーションズ／洲崎西製作委員会', 'site': 'http://suzakinishi.tv/' },
			{ 'title': 'Kuusen Madoushi Kouhosei no Kyoukan', 'credit': '© 2015 諸星悠・甘味みきひろ／ＫＡＤＯＫＡＷＡ 富士見書房刊／E601小隊', 'site': 'http://ku-sen.jp/' },
			{ 'title': 'Junjou Romantica 3', 'credit': '(C)2015 中村春菊／KADOKAWA／ロマンチカくらぶ!!', 'site': 'http://suzukisan.info/' },
			{ 'title': 'Himouto! Umaru-chan', 'credit': '©サンカクヘッド／集英社©2015 サンカクヘッド／集英社, 「干物妹！うまるちゃん」製作委員会', 'site': 'http://umaru-ani.me/' },
			{ 'title': 'Gakkougurashi!', 'credit': '© Nitroplus／海法紀光・千葉サドル・芳文社／がっこうぐらし！製作委員会', 'site': 'http://gakkougurashi.com/' },
			{ 'title': 'Danchigai', 'credit': '©米田和佐／一迅社・夢野団地自治会2015', 'site': 'http://www.dreamcreation.co.jp/danchigai/' },
			{ 'title': 'Kangoku Gakuen', 'credit': '© 平本アキラ・講談社／八光学園裏生徒会 ', 'site': 'http://prison-anime.com/' },
			{ 'title': 'Venus Project: Climax', 'credit': '©GALAT/FormulaVenus実行委員会', 'site': 'http://vproject.jp/' },
			{ 'title': 'Makura no Danshi', 'credit': '© P★P/「枕男子」製作委員会', 'site': 'http://makuranodanshi.com/' },
			{ 'title': 'K-On!', 'credit': '© kakifly・Houbunsha / Sakura High Band', 'site': 'http://www.tbs.co.jp/anime/k-on/' },
			{ 'title': 'Sekkou Boys', 'credit': '© ザリガニワークス・KADOKAWA・ホルベイン画材／石膏ボーイズ製作委員会', 'site': 'http://sekkoboys.com/' },
			{ 'title': 'Ajin', 'credit': '©桜井画門・講談社／亜人管理委員会', 'site': 'http://www.ajin.net/tv/' },
			{ 'title': 'Active Raid: Kidou Kyoushuushitsu Dai-Hakkei', 'credit': '©創通・フィールズ・フライングドッグ／ACTIVERAID PARTNERS', 'site': 'http://activeraid.net/' },
			{ 'title': 'Boku Dake ga Inai Machi', 'credit': '© Kei SANBE　2015／KADOKAWA タイトルロゴ作成：星野ゆきお for VOLARE inc.', 'site': 'http://bokumachi-anime.com/' },
			{ 'title': 'Dagashi Kashi', 'credit': '© 2016 コトヤマ・小学館／シカダ駄菓子', 'site': 'http://www.tbs.co.jp/anime/dagashi/' },
			{ 'title': 'Dimension W', 'credit': '© 岩原裕二 / スクウェアエニックス・DW製作委員会', 'site': 'http://dimension-w.net/' },
			{ 'title': 'Divine Gate', 'credit': '© GungHo Online Entertainment,Inc.／Divine Gate World Council', 'site': 'http://www.marv.jp/special/divinegate/' },
			{ 'title': 'Hai to Gensou no Grimgar', 'credit': '© 2016 十文字青・オーバーラップ／灰と幻想のグリムガル製作委員会', 'site': 'http://grimgar.com/' },
			{ 'title': 'HaruChika: Haruta to Chika wa Seishun Suru', 'credit': '© 2016 初野晴／KADOKAWA／ハルチカ製作委員会', 'site': 'http://haruchika-anime.jp/' },
			{ 'title': 'Kono Subarashii Sekai ni Shukufuku wo!', 'credit': '© 2016 暁なつめ・三嶋くろね／ＫＡＤＯＫＡＷＡ／このすば製作委員会', 'site': 'http://konosuba.com/' },
			{ 'title': 'Musaigen no Phantom World', 'credit': '©秦野宗一郎・京都アニメーション/無彩限のファントム・ワールド製作委員会', 'site': 'http://phantom-world.com/' },
			{ 'title': 'Nijiiro Days', 'credit': '© 水野美波／集英社 © 水野美波／集英社・「虹色デイズ」プロジェクト', 'site': 'http://rainbow-days.tv/' },
			{ 'title': 'Nurse Witch Komugi-chan R', 'credit': '©タツノコプロ／小麦ちゃんＲ 製作委員会', 'site': 'http://www.ntv.co.jp/komugir/' },
			{ 'title': 'Prince of Stride: Alternative', 'credit': '© 2015 FiFS／ＫＡＤＯＫＡＷＡ　アスキー・メディアワークス刊／POSA製作委員会', 'site': 'http://pos-a.jp/' },
			{ 'title': 'Saijaku Muhai no Bahamut', 'credit': '©明月千里・SBクリエイティブ／最弱無敗の製作委員会', 'site': 'http://saijaku.jp/' },
			{ 'title': 'Shoujo-tachi wa Kouya wo Mezasu', 'credit': '©みなとそふと／しょこめざ製作委員会', 'site': 'http://shokomeza.com/' },
			{ 'title': 'Schwarzesmarken', 'credit': '©吉宗鋼紀・ixtl/オルタネイティヴ第二計画', 'site': 'http://schwarzesmarken-anime.jp/' },
			{ 'title': 'Gintama', 'credit': '© Shueisha / Sunrise / Bandai Namco Pictures', 'site': 'http://www.tv-tokyo.co.jp/anime/gintama' },
			{ 'title': 'Shouwa Genroku Rakugo Shinjuu', 'credit': '© 雲田はるこ・講談社／落語心中協会', 'site': 'http://rakugo-shinju-anime.jp/' }
		];
		$scope.title = "World";
	});
}

